### ISSUE TITLE
Submit button does not respond to "enter"

### ISSUE THREAD

**Issue by jdhtwo** [jdhtwo/sagist#5]
It only works with a mouse click, you dodos.

**Comment by jdhtwo** [comment]
Hitting my head against the wall in a couple of areas. My main path has been searching for jQuery events http://api.jquery.com/category/events/ such as .keypress, .on, .bind, etc. I'm not sure if I'm not getting the right syntax or dropping it in the right location, but it's not working.

I had some success using html tags <form></form> in the sense that, when placed properly, they allow "enter to submit" on the text field, but then cause the page to refresh/reset/redraw to a blank screen, so that's no good.

**Comment by mattcroce** [comment]
Addressed in Pull Request #8 - hopefully we can close out an issue!

**Comment by jdhtwo** [comment]
Closed because Matt is an awesome genius!
