### ISSUE TITLE
Text Box Reset

### ISSUE THREAD

**Issue by mattcroce** [jdhtwo/sagist#7]
The value of the text box should reset to blank or should show the placeholder again after the user clicks 'submit' or hits 'enter'

**Comment by jdhtwo** [comment]
Found it. Just need to be at home computer to create the PR.

<pre><code>$('#mushroomsBox').val('');</pre></code>

**Comment by mattcroce** [comment]
Should that go somewhere around line 93 or so, since it should be linked to the click event, right? So this:
$("#mushroomsBox").val('');
should go inside the curly braces that open on line 64 and close on line 93?
Does that make sense or am I a crazy person? That bit of code should go on line 93, the closing curly brace would move to line 94. If I understand it correctly, that should reset the text box with the id of mushroomsBox after the button has been clicked and it's run through the script to re-generate the graph. I dunno.

**Comment by jdhtwo** [comment]
Exactly - it has to be inside that set of curly braces - won't function if it's not the in jQuery <script></script> section, and won't function if it's not in the <pre><code>$("button#submit").click(function() { ... </pre></code> section. I found that it will work in the <pre><code>$("button#submit").click(function() { ... </pre></code> or in the <pre><code>else if((jQuery.trim(inp).length > 0) && (numberRegex.test(inp))) { ... </pre></code> section, but for readability/understanding, I put it on line 94 outside of the <pre><code>else if((jQuery.trim(inp).length > 0) && (numberRegex.test(inp))) { ... </pre></code>  section

**Comment by jdhtwo** [comment]
Obviously, I am getting Markdown happy.

**Comment by jdhtwo** [comment]
Closed when Dan synced on master after making changes outlined above. Dan is a poor GitHub friend.
